"""Full schema

Revision ID: 0cacb96c705f
Revises: 
Create Date: 2026-01-30 00:58:53.418997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cacb96c705f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_assets', sa.Integer(), nullable=True),
    sa.Column('assigned_assets', sa.Integer(), nullable=True),
    sa.Column('completed_assets', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('minor_role', sa.String(length=50), nullable=True),
    sa.Column('minor_role_id', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.String(length=20), nullable=True),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('inspector_points', sa.Integer(), nullable=True),
    sa.Column('specialist_points', sa.Integer(), nullable=True),
    sa.Column('engineer_points', sa.Integer(), nullable=True),
    sa.Column('qe_points', sa.Integer(), nullable=True),
    sa.Column('is_on_leave', sa.Boolean(), nullable=True),
    sa.Column('leave_coverage_for', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("minor_role IN ('inspector', 'specialist', 'engineer', 'quality_engineer') OR minor_role IS NULL", name='check_valid_minor_role'),
    sa.CheckConstraint("role IN ('admin', 'inspector', 'specialist', 'engineer', 'quality_engineer')", name='check_valid_role'),
    sa.CheckConstraint("shift IN ('day', 'night') OR shift IS NULL", name='check_valid_shift'),
    sa.CheckConstraint("specialization IN ('mechanical', 'electrical') OR specialization IS NULL", name='check_valid_specialization'),
    sa.ForeignKeyConstraint(['leave_coverage_for'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minor_role_id'),
    sa.UniqueConstraint('role_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('bonus_stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('awarded_by', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('related_job_type', sa.String(length=30), nullable=True),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.Column('is_qe_request', sa.Boolean(), nullable=True),
    sa.Column('qe_requester_id', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.String(length=20), nullable=True),
    sa.Column('admin_modified_amount', sa.Integer(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 1 AND amount <= 10', name='check_valid_bonus_amount'),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qe_requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_type', 'version', name='uq_template_type_version')
    )
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_templates_equipment_type'), ['equipment_type'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('equipment_type_ar', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('location_ar', sa.String(length=100), nullable=True),
    sa.Column('berth', sa.String(length=20), nullable=True),
    sa.Column('home_berth', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=50), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'under_maintenance', 'out_of_service', 'stopped', 'paused')", name='check_valid_equipment_status'),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_berth'), ['berth'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_equipment_type'), ['equipment_type'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_table('job_takeovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('bonus_awarded', sa.Boolean(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("job_type IN ('specialist', 'engineer', 'inspection')", name='check_valid_takeover_job_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'denied', 'completed')", name='check_valid_takeover_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=30), nullable=False),
    sa.Column('other_reason', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('coverage_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("leave_type IN ('sick', 'annual', 'emergency', 'training', 'other')", name='check_valid_leave_type'),
    sa.CheckConstraint("scope IN ('major_only', 'full')", name='check_valid_leave_scope'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_valid_leave_status'),
    sa.CheckConstraint('date_to >= date_from', name='check_valid_leave_dates'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coverage_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_ar', sa.Text(), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_persistent', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('info', 'warning', 'urgent', 'critical')", name='check_valid_notification_priority'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('pause_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reason_category', sa.String(length=30), nullable=False),
    sa.Column('reason_details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('delegated_to', sa.Integer(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("reason_category IN ('parts', 'duty_finish', 'tools', 'manpower', 'oem', 'other')", name='check_valid_pause_reason'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'denied')", name='check_valid_pause_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('qe_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_category', sa.String(length=50), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('evidence_photos', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_met', sa.Boolean(), nullable=True),
    sa.Column('admin_validation', sa.String(length=20), nullable=True),
    sa.Column('admin_validation_by', sa.Integer(), nullable=True),
    sa.Column('admin_validation_notes', sa.Text(), nullable=True),
    sa.Column('admin_validated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("admin_validation IN ('valid', 'wrong') OR admin_validation IS NULL", name='check_valid_admin_validation'),
    sa.CheckConstraint("job_type IN ('specialist', 'engineer')", name='check_valid_qr_job_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_valid_qr_status'),
    sa.ForeignKeyConstraint(['admin_validation_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qe_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_data', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_queue_user_id'), ['user_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_text_ar', sa.Text(), nullable=True),
    sa.Column('answer_type', sa.Enum('pass_fail', 'yes_no', 'numeric', 'text', name='answer_types'), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('pass_fail_rule', sa.JSON(), nullable=True),
    sa.Column('critical_failure', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("category IN ('mechanical', 'electrical') OR category IS NULL", name='check_valid_item_category'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'order_index', name='uq_item_template_order')
    )
    op.create_table('engineer_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universal_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(length=30), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('major_reason', sa.Text(), nullable=True),
    sa.Column('planned_time_days', sa.Integer(), nullable=True),
    sa.Column('planned_time_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('planned_time_entered_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_time_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paused_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('work_notes', sa.Text(), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=True),
    sa.Column('qe_id', sa.Integer(), nullable=True),
    sa.Column('time_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('qc_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('admin_bonus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('major', 'minor') OR category IS NULL", name='check_valid_eng_job_category'),
    sa.CheckConstraint("job_type IN ('custom_project', 'system_review', 'special_task')", name='check_valid_eng_job_type'),
    sa.CheckConstraint("status IN ('assigned', 'in_progress', 'paused', 'completed', 'incomplete', 'qc_approved')", name='check_valid_eng_job_status'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['qe_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engineer_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engineer_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_engineer_jobs_universal_id'), ['universal_id'], unique=True)

    op.create_table('inspection_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_list_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('berth', sa.String(length=20), nullable=True),
    sa.Column('mechanical_inspector_id', sa.Integer(), nullable=True),
    sa.Column('electrical_inspector_id', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('backlog_triggered', sa.Boolean(), nullable=True),
    sa.Column('backlog_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('mech_completed_at', sa.DateTime(), nullable=True),
    sa.Column('elec_completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_takeover', sa.Boolean(), nullable=True),
    sa.Column('original_assignment_id', sa.Integer(), nullable=True),
    sa.Column('mech_points_awarded', sa.Integer(), nullable=True),
    sa.Column('elec_points_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['electrical_inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['inspection_list_id'], ['inspection_lists.id'], ),
    sa.ForeignKeyConstraint(['mechanical_inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_assignment_id'], ['inspection_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('asset_types', sa.JSON(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='check_valid_day'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'reviewed', name='inspection_status'), nullable=True),
    sa.Column('result', sa.Enum('pass', 'fail', 'incomplete', name='inspection_result'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('reviewed_at IS NULL OR reviewed_at >= submitted_at', name='check_reviewed_after_submit'),
    sa.CheckConstraint('submitted_at IS NULL OR submitted_at >= started_at', name='check_submitted_after_start'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assessment_status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('work_order_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("assessment_status IN ('pending', 'confirmed', 'rejected', 'minor') OR assessment_status IS NULL", name='check_valid_assessment_status'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent') OR priority IS NULL", name='check_valid_priority'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='check_valid_severity'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved', 'closed', 'false_alarm')", name='check_valid_defect_status'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('inspection_assignment_id', sa.Integer(), nullable=False),
    sa.Column('mechanical_inspector_id', sa.Integer(), nullable=False),
    sa.Column('electrical_inspector_id', sa.Integer(), nullable=False),
    sa.Column('mech_verdict', sa.String(length=20), nullable=True),
    sa.Column('elec_verdict', sa.String(length=20), nullable=True),
    sa.Column('final_status', sa.String(length=20), nullable=True),
    sa.Column('urgent_reason', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=20), nullable=True),
    sa.Column('admin_decision_by', sa.Integer(), nullable=True),
    sa.Column('admin_decision_notes', sa.Text(), nullable=True),
    sa.Column('mech_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('elec_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("elec_verdict IN ('operational', 'urgent') OR elec_verdict IS NULL", name='check_valid_elec_verdict'),
    sa.CheckConstraint("final_status IN ('operational', 'urgent') OR final_status IS NULL", name='check_valid_final_status'),
    sa.CheckConstraint("mech_verdict IN ('operational', 'urgent') OR mech_verdict IS NULL", name='check_valid_mech_verdict'),
    sa.ForeignKeyConstraint(['admin_decision_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['electrical_inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['inspection_assignment_id'], ['inspection_assignments.id'], ),
    sa.ForeignKeyConstraint(['mechanical_inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('answer_value', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'checklist_item_id', name='uq_answer_inspection_item')
    )
    op.create_table('inspection_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('rated_by_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('asset_points', sa.Integer(), nullable=True),
    sa.Column('finding_points', sa.Integer(), nullable=True),
    sa.Column('admin_quality_bonus', sa.Integer(), nullable=True),
    sa.CheckConstraint('admin_quality_bonus >= 0 AND admin_quality_bonus <= 10', name='check_valid_quality_bonus'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_valid_rating'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['rated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_table('weekly_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=True),
    sa.Column('last_inspection_id', sa.Integer(), nullable=True),
    sa.Column('last_inspection_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['last_inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'year', 'week_number', name='uq_equipment_week')
    )
    op.create_table('defect_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('technical_notes', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("verdict IN ('confirm', 'reject', 'minor')", name='check_valid_verdict'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_id')
    )
    op.create_table('specialist_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universal_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('major_reason', sa.Text(), nullable=True),
    sa.Column('planned_time_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('planned_time_entered_at', sa.DateTime(), nullable=True),
    sa.Column('details_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('paused_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_time_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('work_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_status', sa.String(length=50), nullable=True),
    sa.Column('incomplete_reason', sa.Text(), nullable=True),
    sa.Column('qe_id', sa.Integer(), nullable=True),
    sa.Column('time_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('qc_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cleaning_rating', sa.Integer(), nullable=True),
    sa.Column('admin_bonus', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('major', 'minor') OR category IS NULL", name='check_valid_job_category'),
    sa.CheckConstraint("completion_status IN ('pass', 'incomplete') OR completion_status IS NULL", name='check_valid_completion_status'),
    sa.CheckConstraint("status IN ('assigned', 'in_progress', 'paused', 'completed', 'incomplete', 'qc_approved')", name='check_valid_job_status'),
    sa.CheckConstraint('admin_bonus >= 0 AND admin_bonus <= 10', name='check_valid_admin_bonus'),
    sa.CheckConstraint('cleaning_rating >= 0 AND cleaning_rating <= 2 OR cleaning_rating IS NULL', name='check_valid_cleaning_rating'),
    sa.CheckConstraint('planned_time_hours > 0 OR planned_time_hours IS NULL', name='check_positive_planned_time'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['qe_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_id')
    )
    with op.batch_alter_table('specialist_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialist_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_specialist_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_specialist_jobs_universal_id'), ['universal_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialist_jobs_universal_id'))
        batch_op.drop_index(batch_op.f('ix_specialist_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_specialist_jobs_job_id'))

    op.drop_table('specialist_jobs')
    op.drop_table('defect_assessments')
    op.drop_table('weekly_completions')
    op.drop_table('inspection_ratings')
    op.drop_table('inspection_answers')
    op.drop_table('final_assessments')
    op.drop_table('defects')
    op.drop_table('inspections')
    op.drop_table('inspection_schedules')
    op.drop_table('inspection_routines')
    op.drop_table('inspection_assignments')
    with op.batch_alter_table('engineer_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engineer_jobs_universal_id'))
        batch_op.drop_index(batch_op.f('ix_engineer_jobs_job_id'))

    op.drop_table('engineer_jobs')
    op.drop_table('checklist_items')
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_queue_created_at'))

    op.drop_table('sync_queue')
    op.drop_table('quality_reviews')
    op.drop_table('pause_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('leaves')
    op.drop_table('job_takeovers')
    op.drop_table('files')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_equipment_type'))
        batch_op.drop_index(batch_op.f('ix_equipment_berth'))

    op.drop_table('equipment')
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_templates_equipment_type'))

    op.drop_table('checklist_templates')
    op.drop_table('bonus_stars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('inspection_lists')
    # ### end Alembic commands ###
