"""Add ImportLog and RoleSwapLog models

Revision ID: 202d95192629
Revises: c2d3e4f5g6h7
Create Date: 2026-02-07 16:51:52.897018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '202d95192629'
down_revision = 'c2d3e4f5g6h7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('created_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_swap_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('old_role', sa.String(length=50), nullable=False),
    sa.Column('old_role_id', sa.String(length=20), nullable=False),
    sa.Column('old_minor_role', sa.String(length=50), nullable=True),
    sa.Column('old_minor_role_id', sa.String(length=20), nullable=True),
    sa.Column('new_role', sa.String(length=50), nullable=False),
    sa.Column('new_role_id', sa.String(length=20), nullable=False),
    sa.Column('new_minor_role', sa.String(length=50), nullable=True),
    sa.Column('new_minor_role_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('equipment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_type_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_scrapped', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('capacity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key('fk_equipment_created_by', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('inspection_answers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ia_photo_file', 'files', ['photo_file_id'], ['id'])
        batch_op.create_foreign_key('fk_ia_voice_note', 'files', ['voice_note_id'], ['id'])
        batch_op.create_foreign_key('fk_ia_video_file', 'files', ['video_file_id'], ['id'])

    with op.batch_alter_table('inspection_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_iassign_template', 'checklist_templates', ['template_id'], ['id'])

    with op.batch_alter_table('inspection_routines', schema=None) as batch_op:
        batch_op.alter_column('shift',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('days_of_week',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inspection_code', ['inspection_code'])
        batch_op.create_foreign_key('fk_insp_assignment', 'inspection_assignments', ['assignment_id'], ['id'])

    with op.batch_alter_table('roster_entries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_roster_user_date', ['user_id', 'date'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_id', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(21)'))
        batch_op.create_index(batch_op.f('ix_users_sap_id'), ['sap_id'], unique=True)
        batch_op.create_foreign_key('fk_users_created_by', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_created_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_sap_id'))
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(21)'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('sap_id')

    with op.batch_alter_table('roster_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roster_user_date', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insp_assignment', type_='foreignkey')
        batch_op.drop_constraint('uq_inspection_code', type_='unique')

    with op.batch_alter_table('inspection_routines', schema=None) as batch_op:
        batch_op.alter_column('days_of_week',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('shift',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('inspection_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iassign_template', type_='foreignkey')

    with op.batch_alter_table('inspection_answers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ia_video_file', type_='foreignkey')
        batch_op.drop_constraint('fk_ia_voice_note', type_='foreignkey')
        batch_op.drop_constraint('fk_ia_photo_file', type_='foreignkey')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_created_by', type_='foreignkey')
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('capacity')
        batch_op.drop_column('is_scrapped')
        batch_op.drop_column('equipment_type_2')

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('equipment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('role_swap_logs')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
