"""Add incomplete workflow fields to specialist_job

Revision ID: aafab42eb030
Revises: 202d95192629
Create Date: 2026-02-07 17:44:50.890839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'aafab42eb030'
down_revision = '202d95192629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping temp table - only exists in SQLite batch operations
    from sqlalchemy import inspect
    from alembic import op
    bind = op.get_bind()
    inspector = inspect(bind)
    if '_alembic_tmp_checklist_templates' in inspector.get_table_names():
        op.drop_table('_alembic_tmp_checklist_templates')
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('equipment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_type_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_scrapped', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('capacity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key('fk_equipment_created_by', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('inspection_answers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_inspection_answers_photo_file', 'files', ['photo_file_id'], ['id'])
        batch_op.create_foreign_key('fk_inspection_answers_voice_note', 'files', ['voice_note_id'], ['id'])
        batch_op.create_foreign_key('fk_inspection_answers_video_file', 'files', ['video_file_id'], ['id'])

    with op.batch_alter_table('inspection_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_inspection_assignments_template', 'checklist_templates', ['template_id'], ['id'])

    with op.batch_alter_table('inspection_routines', schema=None) as batch_op:
        batch_op.alter_column('shift',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('days_of_week',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inspection_code', ['inspection_code'])
        batch_op.create_foreign_key('fk_inspections_assignment', 'inspection_assignments', ['assignment_id'], ['id'])

    with op.batch_alter_table('roster_entries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_roster_user_date', ['user_id', 'date'])

    with op.batch_alter_table('specialist_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incomplete_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('incomplete_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('incomplete_acknowledged_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('incomplete_acknowledged_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('incomplete_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_specialist_jobs_incomplete_acknowledger', 'users', ['incomplete_acknowledged_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_id', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(21)'))
        batch_op.create_index(batch_op.f('ix_users_sap_id'), ['sap_id'], unique=True)
        batch_op.create_foreign_key('fk_users_created_by', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_created_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_sap_id'))
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(21)'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('sap_id')

    with op.batch_alter_table('specialist_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_specialist_jobs_incomplete_acknowledger', type_='foreignkey')
        batch_op.alter_column('incomplete_reason',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('incomplete_acknowledged_at')
        batch_op.drop_column('incomplete_acknowledged_by')
        batch_op.drop_column('incomplete_at')
        batch_op.drop_column('incomplete_notes')

    with op.batch_alter_table('roster_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roster_user_date', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspections_assignment', type_='foreignkey')
        batch_op.drop_constraint('uq_inspection_code', type_='unique')

    with op.batch_alter_table('inspection_routines', schema=None) as batch_op:
        batch_op.alter_column('days_of_week',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('shift',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('inspection_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspection_assignments_template', type_='foreignkey')

    with op.batch_alter_table('inspection_answers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspection_answers_photo_file', type_='foreignkey')
        batch_op.drop_constraint('fk_inspection_answers_voice_note', type_='foreignkey')
        batch_op.drop_constraint('fk_inspection_answers_video_file', type_='foreignkey')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_created_by', type_='foreignkey')
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('capacity')
        batch_op.drop_column('is_scrapped')
        batch_op.drop_column('equipment_type_2')

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('equipment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('_alembic_tmp_checklist_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('name_ar', sa.VARCHAR(length=200), nullable=True),
    sa.Column('equipment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('function', sa.VARCHAR(length=200), nullable=True),
    sa.Column('assembly', sa.VARCHAR(length=200), nullable=True),
    sa.Column('part', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_type', 'version', name=op.f('uq_template_type_version'))
    )
    # ### end Alembic commands ###
