"""Sync schema with models

Revision ID: b9d8a4a0f4db
Revises: d4e5f6g7h8i9
Create Date: 2026-02-04 02:08:30.526319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b9d8a4a0f4db'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_roster_user_date')
    )
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('function', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('assembly', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('part', sa.String(length=200), nullable=True))
        batch_op.alter_column('equipment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('inspection_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('voice_note_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['photo_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['voice_note_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['video_file_id'], ['id'])

    with op.batch_alter_table('inspection_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'checklist_templates', ['template_id'], ['id'])

    with op.batch_alter_table('inspection_routines', schema=None) as batch_op:
        batch_op.alter_column('shift',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('days_of_week',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('inspection_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('berth', sa.String(length=50), nullable=True))

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspection_code', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['inspection_code'])
        batch_op.create_foreign_key(None, 'inspection_assignments', ['assignment_id'], ['id'])

    with op.batch_alter_table('specialist_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wrong_finding_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wrong_finding_photo', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(21)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(21)'))

    with op.batch_alter_table('specialist_jobs', schema=None) as batch_op:
        batch_op.drop_column('wrong_finding_photo')
        batch_op.drop_column('wrong_finding_reason')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('inspection_code')
        batch_op.drop_column('assignment_id')

    with op.batch_alter_table('inspection_schedules', schema=None) as batch_op:
        batch_op.drop_column('berth')
        batch_op.drop_column('shift')

    with op.batch_alter_table('inspection_routines', schema=None) as batch_op:
        batch_op.alter_column('days_of_week',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('shift',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('inspection_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('inspection_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voice_note_id')
        batch_op.drop_column('video_file_id')
        batch_op.drop_column('video_path')
        batch_op.drop_column('photo_file_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('equipment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('part')
        batch_op.drop_column('assembly')
        batch_op.drop_column('function')
        batch_op.drop_column('description')

    op.drop_table('roster_entries')
    # ### end Alembic commands ###
